# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      name: Build
    - run: npm test
      name: Test
    - run: npm run lint
      name: Lint
    - run: cd dist && zip -r ../extension.zip * && cd .. 
      name: Package Extension
    - name: Upload to Artifacts
      if: ${{ github.event_name == 'pull_request' }}
      uses: gavv/pull-request-artifacts@v1.0.0
      with:
        commit: ${{ github.event.pull_request.head.sha }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        artifacts-token: ${{ secrets.ARTIFACT_REPO_SECRET }}
        artifacts-branch: master
        artifacts-repo: textgrab/artifacts
        artifacts-dir: ${{ github.event.pull_request.number }}
        artifacts: |
          extension.zip
    
